//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace d3hiring.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class lesson
    {
        public int idlesson { get; set; }
        public int idteacher { get; set; }
        public int idstudent { get; set; }
    
        public virtual student student { get; set; }
        public virtual teacher teacher { get; set; }
    }
}
